on:
  push:
    branches:
      - main

name: deploy-to-connect

jobs:
  deploy-to-connect:
    runs-on: ubuntu-latest
    env:
      APP_NAME: "demo-palmers-penguins-shiny-github-actions-deploy-2"
      APP_DIR: "app"
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RSCONNECT_APIKEY: ${{ secrets.RSCONNECT_APIKEY }}
    steps:
      - uses: actions/checkout@v2

      - name: Install renv
        run: |
          install.packages("renv")
        shell: Rscript {0}
        
      - name: Restore environment
        run: |
          renv::consent(TRUE)
          renv::restore()
        shell: Rscript {0}

      - name: Generate manifest.json
        run: |
          rsconnect::writeManifest(appDir = "${{ env.APP_DIR }}")
        shell: Rscript {0}
        
      # - name: Deploy to RStudio Connect
      #   uses: rstudio/actions/connect-publish@main
      #   with:
      #     url: https://${{ env.RSCONNECT_APIKEY }}@colorado.rstudio.com/rsc/
      #     access-type: logged_in
      #     show-logs: true
      #     force: true
      #     dir: ${{ env.APP_DIR }}
      #     require-vanity-path: true
        
        
      # rsconnect::connectApiUser(server = "gha-colorado.rstudio.com", apiKey = Sys.getenv("CONNECT_API_KEY"))
      # rsconnect::servers() |> dplyr::select(name, url) |> print()
      - name: addConnectServer
        run: |
          rsconnect::addConnectServer(url = "https://colorado.rstudio.com/rsc/", name = "colorado.rstudio.com")
        shell: Rscript {0}
        
      - name: connectApiUser
        run: |
          rsconnect::connectApiUser(apiKey="{{ env.RSCONNECT_APIKEY }}", account = "sam.edwardes", server = "colorado.rstudio.com")
        shell: Rscript {0}
        
      - name: Publish to connect
        run: |
          rsconnect::deployApp(addDir = "app", appFiles = c("app.R"), appName = "demo-palmers-penguins-shiny-github-actions-deploy", appTitle = "Demo - Palmers Penguins [Shiny / GitHub Actions Deploy]", forceUpdate = TRUE, account = "sam.edwardes")
        shell: Rscript {0}
   